name: CI

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests with coverage
        run: |
          docker network inspect care >/dev/null 2>&1 || \
            docker network create care 
          docker-compose -f docker-compose.local.yaml up -d
          docker exec care bash -c "coverage run manage.py test --settings=config.settings.test --keepdb"
          docker exec care bash -c "coverage report"

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
